### ISSUE TITLE
KeyError while parsing openssl output

### ISSUE THREAD

**Issue by n3storm** [johndoe31415/pdfminify#2]
File "/home/gollum/Proyectos/certs/pdfminify/llpdf/tools/X509Certificate.py", line 44, in _parse_cert
    self._subject = results["issuer= "]
KeyError: 'issuer= '
``

Debian 9, OpenSSL version 1.1.0f  25 May 2017

**Comment by johndoe31415** [comment]
Reopening this one to confirm that it also works on @n3storm 's system. Could you kindly close the issue if it's fixed for you? Thanks so much, Joe.

**Comment by n3storm** [comment]
Back from travel, need one day to check this with my certs in other computer.

**Comment by johndoe31415** [comment]
Assuming this is fixed, closing the issue.
