### ISSUE TITLE
Packaging/Distribution

### ISSUE THREAD

**Issue by mbarkhau** [johndoe31415/pdfminify#6]
Is there any reason that a pypi package/distribution can't be created for this project? I understand that ImageMagick must be installed for this to work.

Would you be interested in contributions?

**Comment by maadjordan** [comment]
I am trying to install and test the program but it seems not easy. as Mbarkhau mentioned above if a pip package was prepared it would be easy to install and test. I've installed python v3.7.7

**Comment by johndoe31415** [comment]
Hi @maadjordan  -- you are completely correct. I have no idea how the issue that @mbarkhau raised almost a year ago fell completely off my radar. Actually, looking at the date, I kindof have an idea; I had just had my daughter then for a few weeks and was probably constantly sleep deprived. Still am :-)

In any case, I wanted to update pdfminify a little bit in any case and it seems I should look into packaging it as well. My apologies for letting this slide for so long. Hope to fix this soon.
